version: "3.6"

services:
  db:
    image: postgres:11.4
    container_name: account-transfer-db
    platform: linux/x86_64
    environment:
      - POSTGRES_DB=account-transfer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  rabbitmq0:
    image: rabbitmq:3.8.9-management
    container_name: account-transfer-rabbitmq
    platform: linux/x86_64
    restart: always
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  db:
    driver: local